spring.application.name=spring0312

spring.datasource.hikari.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.hikari.jdbc-url=jdbc:log4jdbc:mysql://localhost:3306/cloud
spring.datasource.hikari.username=root
spring.datasource.hikari.password=1111

mybatis.configuration.map-underscore-to-camel-case=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB